# Generated by Django 3.0.5 on 2020-05-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='Create_time')),
                ('update_time', models.DateField(auto_now=True, verbose_name='update_time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete_tog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='Create_time')),
                ('update_time', models.DateField(auto_now=True, verbose_name='update_time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete_tog')),
                ('name', models.CharField(max_length=20, verbose_name='Classification_Name')),
                ('logo', models.CharField(max_length=20, verbose_name='Logo')),
                ('image', models.ImageField(upload_to='type', verbose_name='Goods_Species_Image')),
            ],
            options={
                'verbose_name': 'Goods_Species',
                'verbose_name_plural': 'Goods_Species',
                'db_table': 'df_goods_type',
            },
        ),
    ]
